install.packages("dplyr")
install.packages("ggplot2")
midwest <- as.data.frame(ggplot2::midwest)
midwest
head(midwest)
tail(midwest)
summary(midwest)
View(midwest)
str(midwest)
dim(midwest)
library(dplyr)
midwest <- rename(midwest, total = poptotal)
midwest <- rename(midwest, asian = popasian)
dim(midwest)
str(midwest)
View(midwest)
midwest$percent <- midwest$asian / midwest$total * 100
View(midwest)
library(ggplot2)
qplot(midwest$percent)
hist(midwest$percent)
asian_mean <- mean(midwest$percent)
asian_mean
midwest$range <- ifelse(midwest$percent > asian_mean, "large", "small")
View(midwest)
hist(midwest$range)
qplot(midwest$range)
